services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: karka_deh
      POSTGRES_PASSWORD: 86400051
      POSTGRES_DB: karka_deh
    ports:
      - 5432:5432
    # volumes:
    #   - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
 
# volumes:
#   pgdata:
