spring:
  application:
    name: karka_deh
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/verynice
    username: abdullah
    password: 2003
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

jwt:
  secret: verysecurejwtsecretbecauseidontknowwhattoputinhere
